name: Workflow for Codecov Action
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Upload code coverage 
        uses: codecov/codecov-action@v2.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage1.xml
          flags: unittests
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          version: "v0.1.13"
          
         
          
          
        

        
         
  


   
